[package]
name = "mdbook-llms-txt"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = "0.4"
serde_json = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
clap = "4.4"

[dev-dependencies]
similar-asserts = "1.5"
